name: Formatting

on:
  push:
    branches: [ main ]
    paths:
      - "src/**/*.rs"
      - "Cargo.toml"
      - ".github/workflows/fmt.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**/*.rs"
      - "Cargo.toml"
      - ".github/workflows/fmt.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Verify code formatting
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      - name: Install rust (latest stable)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
