name: MSRV

on:
  push:
    branches: [ main ]
    paths:
      - "src/**/*.rs"
      - "Cargo.toml"
      - ".github/workflows/msrv.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**/*.rs"
      - "Cargo.toml"
      - ".github/workflows/msrv.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo msrv
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-msrv@0.16.0-beta.25
      - name: Version of cargo msrv
        run: cargo msrv --version
      - name: Run cargo msrv
        run: cargo msrv --output-format json verify
      - name: Run cargo msrv on verify failure
        if: ${{ failure() }}
        run: cargo msrv find --output-format json
